import { readFileSync, writeFileSync, existsSync, readdirSync, copyFileSync } from 'fs';
import { resolve, join } from 'path';

const PUBLIC_DIR = resolve('build');
const INDEX_PATH = join(PUBLIC_DIR, 'index.html');
const FAVICON_SRC = resolve('static/favicon.svg');
const LEGACY_PUBLIC_DIR = resolve('../public');

const GUIDE_FOR_FRONTEND = `
<!--
  This is a single file build of the frontend.
  It is automatically generated by the build process.
  Do not edit this file directly.
  To make changes, refer to the "Web UI" section in the README.
-->
`.trim();

async function main() {
    if (!existsSync(INDEX_PATH)) {
        console.error('Error: index.html not found at', INDEX_PATH);
        process.exit(1);
    }

    let content = readFileSync(INDEX_PATH, 'utf-8');

    // Inline favicon
    if (existsSync(FAVICON_SRC)) {
        const faviconContent = readFileSync(FAVICON_SRC);
        const faviconBase64 = faviconContent.toString('base64');
        const faviconDataUrl = `data:image/svg+xml;base64,${faviconBase64}`;
        content = content.replace(/href="[^"]*favicon\.svg"/g, `href="${faviconDataUrl}"`);
        console.log('✓ Inlined favicon.svg');
    }

    content = content.replace(/\r/g, '');
    content = GUIDE_FOR_FRONTEND + '\n' + content;

    // Find and copy bundle files
    const immutableDir = join(PUBLIC_DIR, '_app/immutable');
    const assetsDir = join(immutableDir, 'assets');

    let jsBundle = '';
    let cssBundle = '';

    if (existsSync(immutableDir)) {
        const jsFiles = readdirSync(immutableDir).filter(f => f.match(/^bundle\..+\.js$/));
        if (jsFiles.length > 0) {
            jsBundle = jsFiles[0];
            copyFileSync(join(immutableDir, jsBundle), join(PUBLIC_DIR, 'bundle.js'));
            console.log(`✓ Copied ${jsBundle} -> bundle.js`);
        } else {
            console.error('Error: No JS bundle found in', immutableDir);
            process.exit(1);
        }
    } else {
        console.error('Error: _app/immutable directory not found at', immutableDir);
        process.exit(1);
    }

    if (existsSync(assetsDir)) {
        const cssFiles = readdirSync(assetsDir).filter(f => f.match(/^bundle\..+\.css$/));
        if (cssFiles.length > 0) {
            cssBundle = cssFiles[0];
            copyFileSync(join(assetsDir, cssBundle), join(PUBLIC_DIR, 'bundle.css'));
            console.log(`✓ Copied ${cssBundle} -> bundle.css`);
        } else {
            console.warn('Warning: No CSS bundle found in', assetsDir);
        }
    }

    // Replace paths in index.html
    if (jsBundle) {
        const jsRegex = new RegExp(`(["'])/_app/immutable/${jsBundle.replaceAll('.', '\\.')}(["'])`, 'g');
        content = content.replaceAll(jsRegex, '$1./bundle.js$2');
        // Handle import() in script
        const importRegex = new RegExp(`import\\((["'])/_app/immutable/${jsBundle.replaceAll('.', '\\.')}(["'])\\)`, 'g');
        content = content.replaceAll(importRegex, 'import($1./bundle.js$2)');
    }

    if (cssBundle) {
        const cssRegex = new RegExp(`(["'])/_app/immutable/assets/${cssBundle.replaceAll('.', '\\.')}(["'])`, 'g');
        content = content.replaceAll(cssRegex, '$1./bundle.css$2');
    }

    writeFileSync(INDEX_PATH, content, 'utf-8');
    console.log('✓ Updated index.html');

    // Mirror to legacy public dir for Python server
    import('fs').then(fs => {
        if (!fs.existsSync(LEGACY_PUBLIC_DIR)) fs.mkdirSync(LEGACY_PUBLIC_DIR, { recursive: true });
        const files = fs.readdirSync(PUBLIC_DIR);
        for (const file of files) {
            const src = join(PUBLIC_DIR, file);
            const dest = join(LEGACY_PUBLIC_DIR, file);
            if (fs.statSync(src).isFile()) {
                fs.copyFileSync(src, dest);
            }
        }
        console.log('✓ Mirrored build to ../public for Python server');
    });
}

main().catch(console.error);
